//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Artist {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.Resources.Views.Artist.EditStrings", typeof(EditStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist type.
        /// </summary>
        public static string BaArtistType {
            get {
                return ResourceManager.GetString("BaArtistType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base voicebank.
        /// </summary>
        public static string BaBaseVoicebank {
            get {
                return ResourceManager.GetString("BaBaseVoicebank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string BaDescription {
            get {
                return ResourceManager.GetString("BaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups and circles.
        /// </summary>
        public static string BaGroups {
            get {
                return ResourceManager.GetString("BaGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main picture.
        /// </summary>
        public static string BaMainPicture {
            get {
                return ResourceManager.GetString("BaMainPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary name (in one or more languages).
        /// </summary>
        public static string BaNames {
            get {
                return ResourceManager.GetString("BaNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed types: {0}. Maximum size is {1} MB..
        /// </summary>
        public static string BaPictureInfo {
            get {
                return ResourceManager.GetString("BaPictureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voicebank release date.
        /// </summary>
        public static string BaReleaseDate {
            get {
                return ResourceManager.GetString("BaReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit artist - {0}.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string PiAdd {
            get {
                return ResourceManager.GetString("PiAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture description.
        /// </summary>
        public static string PiPictureDescription {
            get {
                return ResourceManager.GetString("PiPictureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please only upload pictures relevant to this artist, nothing else..
        /// </summary>
        public static string PiPicturesNote {
            get {
                return ResourceManager.GetString("PiPicturesNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional pictures.
        /// </summary>
        public static string TabAdditionalPictures {
            get {
                return ResourceManager.GetString("TabAdditionalPictures", resourceCulture);
            }
        }
    }
}
