//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArtistRoleNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArtistRoleNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.App_GlobalResources.ArtistRoleNames", typeof(ArtistRoleNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animator.
        /// </summary>
        public static string Animator {
            get {
                return ResourceManager.GetString("Animator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arranger.
        /// </summary>
        public static string Arranger {
            get {
                return ResourceManager.GetString("Arranger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chorus.
        /// </summary>
        public static string Chorus {
            get {
                return ResourceManager.GetString("Chorus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer.
        /// </summary>
        public static string Composer {
            get {
                return ResourceManager.GetString("Composer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor.
        /// </summary>
        public static string Distributor {
            get {
                return ResourceManager.GetString("Distributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder.
        /// </summary>
        public static string Encoder {
            get {
                return ResourceManager.GetString("Encoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustrator.
        /// </summary>
        public static string Illustrator {
            get {
                return ResourceManager.GetString("Illustrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumentalist.
        /// </summary>
        public static string Instrumentalist {
            get {
                return ResourceManager.GetString("Instrumentalist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyricist.
        /// </summary>
        public static string Lyricist {
            get {
                return ResourceManager.GetString("Lyricist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mastering.
        /// </summary>
        public static string Mastering {
            get {
                return ResourceManager.GetString("Mastering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer.
        /// </summary>
        public static string Mixer {
            get {
                return ResourceManager.GetString("Mixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocal data provider.
        /// </summary>
        public static string VocalDataProvider {
            get {
                return ResourceManager.GetString("VocalDataProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocalist.
        /// </summary>
        public static string Vocalist {
            get {
                return ResourceManager.GetString("Vocalist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice manipulator.
        /// </summary>
        public static string VoiceManipulator {
            get {
                return ResourceManager.GetString("VoiceManipulator", resourceCulture);
            }
        }
    }
}
