//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class CommonMessages
	{
		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal CommonMessages()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.App_GlobalResources.CommonMessages", typeof(CommonMessages).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This entry has been deleted. It is still temporarily accessible, but won&apos;t show up in any of the listings..
		/// </summary>
		public static string EntryDeleted
		{
			get
			{
				return ResourceManager.GetString("EntryDeleted", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This entry was merged to.
		/// </summary>
		public static string EntryMergedTo
		{
			get
			{
				return ResourceManager.GetString("EntryMergedTo", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Draft = entry is missing crucial information. This status indicates that you&apos;re requesting additional information to be added or corrected.&lt;br /&gt;
		///Finished = The entry has all the necessary information, but it hasn&apos;t been inspected by a trusted user yet.&lt;br /&gt;
		///Approved = The entry has been inspected and approved by a trusted user. Approved entries can only be edited by trusted users..
		/// </summary>
		public static string EntryStatusExplanation
		{
			get
			{
				return ResourceManager.GetString("EntryStatusExplanation", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This entry is locked, meaning that only moderators are allowed to edit it..
		/// </summary>
		public static string Locked
		{
			get
			{
				return ResourceManager.GetString("Locked", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Choose the language for this name. &quot;Original&quot; is the name in original language that isn&apos;t English, for example Japanese. If the original language is English, do not input a name in the &quot;Original&quot; language..
		/// </summary>
		public static string NameLanguageHelp
		{
			get
			{
				return ResourceManager.GetString("NameLanguageHelp", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This page revision has been hidden..
		/// </summary>
		public static string RevisionHidden
		{
			get
			{
				return ResourceManager.GetString("RevisionHidden", resourceCulture);
			}
		}
	}
}
