//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PermissionTokenNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PermissionTokenNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.App_GlobalResources.PermissionTokenNames", typeof(PermissionTokenNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access manage menu.
        /// </summary>
        public static string AccessManageMenu {
            get {
                return ResourceManager.GetString("AccessManageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add raw media.
        /// </summary>
        public static string AddRawFileMedia {
            get {
                return ResourceManager.GetString("AddRawFileMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database admin tasks.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add any tag to entry.
        /// </summary>
        public static string ApplyAnyTag {
            get {
                return ResourceManager.GetString("ApplyAnyTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve entries.
        /// </summary>
        public static string ApproveEntries {
            get {
                return ResourceManager.GetString("ApproveEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk delete PVs.
        /// </summary>
        public static string BulkDeletePVs {
            get {
                return ResourceManager.GetString("BulkDeletePVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create comments.
        /// </summary>
        public static string CreateComments {
            get {
                return ResourceManager.GetString("CreateComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete comments.
        /// </summary>
        public static string DeleteComments {
            get {
                return ResourceManager.GetString("DeleteComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete entries.
        /// </summary>
        public static string DeleteEntries {
            get {
                return ResourceManager.GetString("DeleteEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designated staff member.
        /// </summary>
        public static string DesignatedStaff {
            get {
                return ResourceManager.GetString("DesignatedStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable users.
        /// </summary>
        public static string DisableUsers {
            get {
                return ResourceManager.GetString("DisableUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit all song lists.
        /// </summary>
        public static string EditAllSongLists {
            get {
                return ResourceManager.GetString("EditAllSongLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage featured songlists.
        /// </summary>
        public static string EditFeaturedLists {
            get {
                return ResourceManager.GetString("EditFeaturedLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage news.
        /// </summary>
        public static string EditNews {
            get {
                return ResourceManager.GetString("EditNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit personal profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit tags.
        /// </summary>
        public static string EditTags {
            get {
                return ResourceManager.GetString("EditTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock entries.
        /// </summary>
        public static string LockEntries {
            get {
                return ResourceManager.GetString("LockEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage database.
        /// </summary>
        public static string ManageDatabase {
            get {
                return ResourceManager.GetString("ManageDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage entry reports.
        /// </summary>
        public static string ManageEntryReports {
            get {
                return ResourceManager.GetString("ManageEntryReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage event series.
        /// </summary>
        public static string ManageEventSeries {
            get {
                return ResourceManager.GetString("ManageEventSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage IP rules.
        /// </summary>
        public static string ManageIPRules {
            get {
                return ResourceManager.GetString("ManageIPRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage user permissions.
        /// </summary>
        public static string ManageUserPermissions {
            get {
                return ResourceManager.GetString("ManageUserPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge entries.
        /// </summary>
        public static string MergeEntries {
            get {
                return ResourceManager.GetString("MergeEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album import.
        /// </summary>
        public static string MikuDbImport {
            get {
                return ResourceManager.GetString("MikuDbImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to trash.
        /// </summary>
        public static string MoveToTrash {
            get {
                return ResourceManager.GetString("MoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read recent comments.
        /// </summary>
        public static string ReadRecentComments {
            get {
                return ResourceManager.GetString("ReadRecentComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove database editing permissions.
        /// </summary>
        public static string RemoveEditPermission {
            get {
                return ResourceManager.GetString("RemoveEditPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove tag usages.
        /// </summary>
        public static string RemoveTagUsages {
            get {
                return ResourceManager.GetString("RemoveTagUsages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore revisions.
        /// </summary>
        public static string RestoreRevisions {
            get {
                return ResourceManager.GetString("RestoreRevisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload own media.
        /// </summary>
        public static string UploadMedia {
            get {
                return ResourceManager.GetString("UploadMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View event log.
        /// </summary>
        public static string ViewAuditLog {
            get {
                return ResourceManager.GetString("ViewAuditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View hidden ratings.
        /// </summary>
        public static string ViewHiddenRatings {
            get {
                return ResourceManager.GetString("ViewHiddenRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View hidden revisions.
        /// </summary>
        public static string ViewHiddenRevisions {
            get {
                return ResourceManager.GetString("ViewHiddenRevisions", resourceCulture);
            }
        }
    }
}
