//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class ReleaseEventEditableFieldNames
	{
		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ReleaseEventEditableFieldNames()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.App_GlobalResources.ReleaseEventEditableFieldNames", typeof(ReleaseEventEditableFieldNames).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Artists.
		/// </summary>
		public static string Artists
		{
			get
			{
				return ResourceManager.GetString("Artists", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Category.
		/// </summary>
		public static string Category
		{
			get
			{
				return ResourceManager.GetString("Category", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Date.
		/// </summary>
		public static string Date
		{
			get
			{
				return ResourceManager.GetString("Date", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Description.
		/// </summary>
		public static string Description
		{
			get
			{
				return ResourceManager.GetString("Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Main picture.
		/// </summary>
		public static string MainPicture
		{
			get
			{
				return ResourceManager.GetString("MainPicture", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Names.
		/// </summary>
		public static string Names
		{
			get
			{
				return ResourceManager.GetString("Names", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Default name language.
		/// </summary>
		public static string OriginalName
		{
			get
			{
				return ResourceManager.GetString("OriginalName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to PVs.
		/// </summary>
		public static string PVs
		{
			get
			{
				return ResourceManager.GetString("PVs", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Series.
		/// </summary>
		public static string Series
		{
			get
			{
				return ResourceManager.GetString("Series", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Series number.
		/// </summary>
		public static string SeriesNumber
		{
			get
			{
				return ResourceManager.GetString("SeriesNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Series suffix.
		/// </summary>
		public static string SeriesSuffix
		{
			get
			{
				return ResourceManager.GetString("SeriesSuffix", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Setlist.
		/// </summary>
		public static string SongList
		{
			get
			{
				return ResourceManager.GetString("SongList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Status.
		/// </summary>
		public static string Status
		{
			get
			{
				return ResourceManager.GetString("Status", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Venue.
		/// </summary>
		public static string Venue
		{
			get
			{
				return ResourceManager.GetString("Venue", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Venue name.
		/// </summary>
		public static string VenueName
		{
			get
			{
				return ResourceManager.GetString("VenueName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to External links.
		/// </summary>
		public static string WebLinks
		{
			get
			{
				return ResourceManager.GetString("WebLinks", resourceCulture);
			}
		}
	}
}
