//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class SongEditableFieldNames
	{
		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal SongEditableFieldNames()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.App_GlobalResources.SongEditableFieldNames", typeof(SongEditableFieldNames).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Artists.
		/// </summary>
		public static string Artists
		{
			get
			{
				return ResourceManager.GetString("Artists", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Groups.
		/// </summary>
		public static string Groups
		{
			get
			{
				return ResourceManager.GetString("Groups", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Duration.
		/// </summary>
		public static string Length
		{
			get
			{
				return ResourceManager.GetString("Length", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Lyrics.
		/// </summary>
		public static string Lyrics
		{
			get
			{
				return ResourceManager.GetString("Lyrics", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Names.
		/// </summary>
		public static string Names
		{
			get
			{
				return ResourceManager.GetString("Names", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Description.
		/// </summary>
		public static string Notes
		{
			get
			{
				return ResourceManager.GetString("Notes", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Nothing.
		/// </summary>
		public static string Nothing
		{
			get
			{
				return ResourceManager.GetString("Nothing", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Original name.
		/// </summary>
		public static string OriginalName
		{
			get
			{
				return ResourceManager.GetString("OriginalName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Original version.
		/// </summary>
		public static string OriginalVersion
		{
			get
			{
				return ResourceManager.GetString("OriginalVersion", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Publish date.
		/// </summary>
		public static string PublishDate
		{
			get
			{
				return ResourceManager.GetString("PublishDate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to PVs.
		/// </summary>
		public static string PVs
		{
			get
			{
				return ResourceManager.GetString("PVs", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Release event.
		/// </summary>
		public static string ReleaseEvent
		{
			get
			{
				return ResourceManager.GetString("ReleaseEvent", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Song type.
		/// </summary>
		public static string SongType
		{
			get
			{
				return ResourceManager.GetString("SongType", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Status.
		/// </summary>
		public static string Status
		{
			get
			{
				return ResourceManager.GetString("Status", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to External links.
		/// </summary>
		public static string WebLinks
		{
			get
			{
				return ResourceManager.GetString("WebLinks", resourceCulture);
			}
		}
	}
}
