//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class TagEditableFieldNames
	{
		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal TagEditableFieldNames()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.App_GlobalResources.TagEditableFieldNames", typeof(TagEditableFieldNames).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Aliased to.
		/// </summary>
		public static string AliasedTo
		{
			get
			{
				return ResourceManager.GetString("AliasedTo", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Category.
		/// </summary>
		public static string CategoryName
		{
			get
			{
				return ResourceManager.GetString("CategoryName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Description.
		/// </summary>
		public static string Description
		{
			get
			{
				return ResourceManager.GetString("Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Hide from suggestions.
		/// </summary>
		public static string HideFromSuggestions
		{
			get
			{
				return ResourceManager.GetString("HideFromSuggestions", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Names.
		/// </summary>
		public static string Names
		{
			get
			{
				return ResourceManager.GetString("Names", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Default name language.
		/// </summary>
		public static string OriginalName
		{
			get
			{
				return ResourceManager.GetString("OriginalName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Parent.
		/// </summary>
		public static string Parent
		{
			get
			{
				return ResourceManager.GetString("Parent", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Picture.
		/// </summary>
		public static string Picture
		{
			get
			{
				return ResourceManager.GetString("Picture", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Related tags.
		/// </summary>
		public static string RelatedTags
		{
			get
			{
				return ResourceManager.GetString("RelatedTags", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Status.
		/// </summary>
		public static string Status
		{
			get
			{
				return ResourceManager.GetString("Status", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Targets.
		/// </summary>
		public static string Targets
		{
			get
			{
				return ResourceManager.GetString("Targets", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to External links.
		/// </summary>
		public static string WebLinks
		{
			get
			{
				return ResourceManager.GetString("WebLinks", resourceCulture);
			}
		}
	}
}
