//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VocaDb.Web.Resources.Views.Shared
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class TimeStrings
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal TimeStrings()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.Resources.Views.Shared.TimeStrings", typeof(TimeStrings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to days.
		/// </summary>
		public static string Days
		{
			get
			{
				return ResourceManager.GetString("Days", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to hours.
		/// </summary>
		public static string Hours
		{
			get
			{
				return ResourceManager.GetString("Hours", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to minutes.
		/// </summary>
		public static string Minutes
		{
			get
			{
				return ResourceManager.GetString("Minutes", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to months.
		/// </summary>
		public static string Months
		{
			get
			{
				return ResourceManager.GetString("Months", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} {1} ago.
		/// </summary>
		public static string TimeAgo
		{
			get
			{
				return ResourceManager.GetString("TimeAgo", resourceCulture);
			}
		}
	}
}
