//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Song {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.Resources.Views.Song.CreateStrings", typeof(CreateStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producers, vocalists and Vocaloids associated with this song..
        /// </summary>
        public static string ArtistDesc {
            get {
                return ResourceManager.GetString("ArtistDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the artist cannot be found it probably hasn&apos;t been added yet. Check other possible spellings of that artist&apos;s name, and if you&apos;re confident there&apos;s no entry yet, please create one using the &quot;Add an artist&quot; menu. You can do this after the song has already been created. You can&apos;t create the artist on this page..
        /// </summary>
        public static string ArtistHelp {
            get {
                return ResourceManager.GetString("ArtistHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists (need at least 1).
        /// </summary>
        public static string ArtistsInfo {
            get {
                return ResourceManager.GetString("ArtistsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This entry is a draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems this PV has already been added to the database..
        /// </summary>
        public static string DuplicatePV {
            get {
                return ResourceManager.GetString("DuplicatePV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (need at least one).
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the entry has a non-English (for example Japanese) name, or if the language of the name is unknown, input that into the Non-English name field. If known, input the romanized name as well. If the official name of the entry is in English, or the there is a known English translation, input that into the English name field..
        /// </summary>
        public static string NameHelp {
            get {
                return ResourceManager.GetString("NameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need at least one artist..
        /// </summary>
        public static string NeedArtist {
            get {
                return ResourceManager.GetString("NeedArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not enter artist names into the name field. Instead, use the artists list..
        /// </summary>
        public static string NoArtistsToName {
            get {
                return ResourceManager.GetString("NoArtistsToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL to the original PV (such as NicoNicoDouga or YouTube).
        /// </summary>
        public static string OriginalPV {
            get {
                return ResourceManager.GetString("OriginalPV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is any of these the original version?.
        /// </summary>
        public static string OriginalSuggestionsTitle {
            get {
                return ResourceManager.GetString("OriginalSuggestionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL to the reprint of the PV (such as NicoNicoDouga or YouTube).
        /// </summary>
        public static string ReprintPV {
            get {
                return ResourceManager.GetString("ReprintPV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song type.
        /// </summary>
        public static string SongType {
            get {
                return ResourceManager.GetString("SongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new song to the database.
        /// </summary>
        public static string SubmitSong {
            get {
                return ResourceManager.GetString("SubmitSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create song. Please correct the errors and try again..
        /// </summary>
        public static string UnableToCreateSong {
            get {
                return ResourceManager.GetString("UnableToCreateSong", resourceCulture);
            }
        }
    }
}
