//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Song {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DetailsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DetailsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.Resources.Views.Song.DetailsStrings", typeof(DetailsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to custom list.
        /// </summary>
        public static string AddToCustomList {
            get {
                return ResourceManager.GetString("AddToCustomList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to list.
        /// </summary>
        public static string AddToList {
            get {
                return ResourceManager.GetString("AddToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string AddToListNotes {
            get {
                return ResourceManager.GetString("AddToListNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate versions.
        /// </summary>
        public static string AlternateVersions {
            get {
                return ResourceManager.GetString("AlternateVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animators.
        /// </summary>
        public static string Animators {
            get {
                return ResourceManager.GetString("Animators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band/unit.
        /// </summary>
        public static string Band {
            get {
                return ResourceManager.GetString("Band", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom lists.
        /// </summary>
        public static string CustomLists {
            get {
                return ResourceManager.GetString("CustomLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed.
        /// </summary>
        public static string Embed {
            get {
                return ResourceManager.GetString("Embed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorited by.
        /// </summary>
        public static string FavoritedByTitle {
            get {
                return ResourceManager.GetString("FavoritedByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} favorite(s).
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liked by.
        /// </summary>
        public static string LikedByTitle {
            get {
                return ResourceManager.GetString("LikedByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} like(s).
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured.
        /// </summary>
        public static string ListsTabFeatured {
            get {
                return ResourceManager.GetString("ListsTabFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New list.
        /// </summary>
        public static string ListsTabNew {
            get {
                return ResourceManager.GetString("ListsTabNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal lists.
        /// </summary>
        public static string ListsTabPersonal {
            get {
                return ResourceManager.GetString("ListsTabPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics.
        /// </summary>
        public static string Lyrics {
            get {
                return ResourceManager.GetString("Lyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string LyricsFrom {
            get {
                return ResourceManager.GetString("LyricsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string LyricsLanguageOther {
            get {
                return ResourceManager.GetString("LyricsLanguageOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lyrics.
        /// </summary>
        public static string LyricsLC {
            get {
                return ResourceManager.GetString("LyricsLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + {0} other(s).
        /// </summary>
        public static string LyricsPlusOthers {
            get {
                return ResourceManager.GetString("LyricsPlusOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching artists.
        /// </summary>
        public static string MatchingArtists {
            get {
                return ResourceManager.GetString("MatchingArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching likes.
        /// </summary>
        public static string MatchingLikes {
            get {
                return ResourceManager.GetString("MatchingLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching tags.
        /// </summary>
        public static string MatchingTags {
            get {
                return ResourceManager.GetString("MatchingTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New list name.
        /// </summary>
        public static string NewListName {
            get {
                return ResourceManager.GetString("NewListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check NicoMimi for download.
        /// </summary>
        public static string NicoMimiDownload {
            get {
                return ResourceManager.GetString("NicoMimiDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original media.
        /// </summary>
        public static string OriginalMedia {
            get {
                return ResourceManager.GetString("OriginalMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original version.
        /// </summary>
        public static string OriginalVersion {
            get {
                return ResourceManager.GetString("OriginalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other artists.
        /// </summary>
        public static string OtherArtists {
            get {
                return ResourceManager.GetString("OtherArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other media.
        /// </summary>
        public static string OtherMedia {
            get {
                return ResourceManager.GetString("OtherMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pools and song lists.
        /// </summary>
        public static string PoolsAndLists {
            get {
                return ResourceManager.GetString("PoolsAndLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producers.
        /// </summary>
        public static string Producers {
            get {
                return ResourceManager.GetString("Producers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published at {0} by {1}..
        /// </summary>
        public static string PVDescription {
            get {
                return ResourceManager.GetString("PVDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PV.
        /// </summary>
        public static string PVDetails {
            get {
                return ResourceManager.GetString("PVDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (PV is unavailable).
        /// </summary>
        public static string PVUnavailable {
            get {
                return ResourceManager.GetString("PVUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related songs.
        /// </summary>
        public static string RelatedSongs {
            get {
                return ResourceManager.GetString("RelatedSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release event.
        /// </summary>
        public static string ReleaseEvent {
            get {
                return ResourceManager.GetString("ReleaseEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear my rating.
        /// </summary>
        public static string RemoveFromFavorites {
            get {
                return ResourceManager.GetString("RemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search YouTube.
        /// </summary>
        public static string SearchYoutube {
            get {
                return ResourceManager.GetString("SearchYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more related songs.
        /// </summary>
        public static string SeeRelatedSongs {
            get {
                return ResourceManager.GetString("SeeRelatedSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string ShowAllVersions {
            get {
                return ResourceManager.GetString("ShowAllVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        public static string SongDetails {
            get {
                return ResourceManager.GetString("SongDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song in lists.
        /// </summary>
        public static string SongInLists {
            get {
                return ResourceManager.GetString("SongInLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song ratings.
        /// </summary>
        public static string SongRatings {
            get {
                return ResourceManager.GetString("SongRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users who liked this also liked.
        /// </summary>
        public static string SuggestionsTitle {
            get {
                return ResourceManager.GetString("SuggestionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} total score.
        /// </summary>
        public static string TotalScore {
            get {
                return ResourceManager.GetString("TotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track #{0} on album {1}.
        /// </summary>
        public static string TrackOnAlbum {
            get {
                return ResourceManager.GetString("TrackOnAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track #{0} on disc {1} on album {2}.
        /// </summary>
        public static string TrackOnAlbumDisc {
            get {
                return ResourceManager.GetString("TrackOnAlbumDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all lists ({0}).
        /// </summary>
        public static string ViewAllLists {
            get {
                return ResourceManager.GetString("ViewAllLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View on external site.
        /// </summary>
        public static string ViewExternal {
            get {
                return ResourceManager.GetString("ViewExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocalists.
        /// </summary>
        public static string Vocalists {
            get {
                return ResourceManager.GetString("Vocalists", resourceCulture);
            }
        }
    }
}
