//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Song {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.Resources.Views.Song.EditStrings", typeof(EditStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ArActions {
            get {
                return ResourceManager.GetString("ArActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add artist.
        /// </summary>
        public static string ArAddArtistTitle {
            get {
                return ResourceManager.GetString("ArAddArtistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string ArArtist {
            get {
                return ResourceManager.GetString("ArArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that you can tag artists for a song much faster after tagging the album first..
        /// </summary>
        public static string ArArtistsNote {
            get {
                return ResourceManager.GetString("ArArtistsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string ArRoles {
            get {
                return ResourceManager.GetString("ArRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string ArSupport {
            get {
                return ResourceManager.GetString("ArSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocaloids, UTAUs and other singing synthesizer voicebanks are added as artists as well..
        /// </summary>
        public static string ArVocaloidsNote {
            get {
                return ResourceManager.GetString("ArVocaloidsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (minutes and seconds).
        /// </summary>
        public static string BaDuration {
            get {
                return ResourceManager.GetString("BaDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary name (in one or more languages).
        /// </summary>
        public static string BaNames {
            get {
                return ResourceManager.GetString("BaNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string BaNotes {
            get {
                return ResourceManager.GetString("BaNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original version.
        /// </summary>
        public static string BaOriginalVersion {
            get {
                return ResourceManager.GetString("BaOriginalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the original version of this song exists on the site, use this field to link this derived version to the original. Choose the song by searching by song title..
        /// </summary>
        public static string BaOriginalVersionHelp {
            get {
                return ResourceManager.GetString("BaOriginalVersionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish date.
        /// </summary>
        public static string BaPublishDate {
            get {
                return ResourceManager.GetString("BaPublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date when this song was first published (either on an album or online).
        /// </summary>
        public static string BaPublishDateHelp {
            get {
                return ResourceManager.GetString("BaPublishDateHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song type.
        /// </summary>
        public static string BaSongType {
            get {
                return ResourceManager.GetString("BaSongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use album release date.
        /// </summary>
        public static string BaUseAlbumDate {
            get {
                return ResourceManager.GetString("BaUseAlbumDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use event date.
        /// </summary>
        public static string BaUseEventDate {
            get {
                return ResourceManager.GetString("BaUseEventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use PV date.
        /// </summary>
        public static string BaUsePvDate {
            get {
                return ResourceManager.GetString("BaUsePvDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit song {0}.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add translation.
        /// </summary>
        public static string LyAddRow {
            get {
                return ResourceManager.GetString("LyAddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics are by default inherited from the original version. They do not need to be specified for the derived versions unless they are different..
        /// </summary>
        public static string LyInheritanceNote {
            get {
                return ResourceManager.GetString("LyInheritanceNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string LyLanguage {
            get {
                return ResourceManager.GetString("LyLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string LySource {
            get {
                return ResourceManager.GetString("LySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add media.
        /// </summary>
        public static string PvAddMedia {
            get {
                return ResourceManager.GetString("PvAddMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string PvAuthor {
            get {
                return ResourceManager.GetString("PvAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string PvDate {
            get {
                return ResourceManager.GetString("PvDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that instrumental versions are to be added in external links instead of media..
        /// </summary>
        public static string PvInstrumentalNote {
            get {
                return ResourceManager.GetString("PvInstrumentalNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string PvLength {
            get {
                return ResourceManager.GetString("PvLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PvName {
            get {
                return ResourceManager.GetString("PvName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string PvNewType {
            get {
                return ResourceManager.GetString("PvNewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string PvService {
            get {
                return ResourceManager.GetString("PvService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PvStatus {
            get {
                return ResourceManager.GetString("PvStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the PV is deleted or hidden by the author and thus unplayable, it should be marked as &quot;Unavailable&quot; here..
        /// </summary>
        public static string PvStatusHelp {
            get {
                return ResourceManager.GetString("PvStatusHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported services: YouTube, NicoNico, Vimeo, SoundCloud, Piapro, Bilibili, Creofuga and Bandcamp (tracks only)..
        /// </summary>
        public static string PvSupportedServices {
            get {
                return ResourceManager.GetString("PvSupportedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string PvType {
            get {
                return ResourceManager.GetString("PvType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        public static string PvUrl {
            get {
                return ResourceManager.GetString("PvUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string TabArtists {
            get {
                return ResourceManager.GetString("TabArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic info.
        /// </summary>
        public static string TabBasicInfo {
            get {
                return ResourceManager.GetString("TabBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics.
        /// </summary>
        public static string TabLyrics {
            get {
                return ResourceManager.GetString("TabLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string TabMedia {
            get {
                return ResourceManager.GetString("TabMedia", resourceCulture);
            }
        }
    }
}
