//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntryDetailsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntryDetailsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.Resources.Views.Shared.EntryDetailsStrings", typeof(EntryDetailsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition date.
        /// </summary>
        public static string AdditionDate {
            get {
                return ResourceManager.GetString("AdditionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pictures.
        /// </summary>
        public static string AllPictures {
            get {
                return ResourceManager.GetString("AllPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic info.
        /// </summary>
        public static string BasicInfoTab {
            get {
                return ResourceManager.GetString("BasicInfoTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this comment?.
        /// </summary>
        public static string ConfirmDeleteComment {
            get {
                return ResourceManager.GetString("ConfirmDeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion.
        /// </summary>
        public static string DiscussionTab {
            get {
                return ResourceManager.GetString("DiscussionTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit tags.
        /// </summary>
        public static string EditTags {
            get {
                return ResourceManager.GetString("EditTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External links.
        /// </summary>
        public static string ExternalLinks {
            get {
                return ResourceManager.GetString("ExternalLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hit(s).
        /// </summary>
        public static string Hits {
            get {
                return ResourceManager.GetString("Hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest comments.
        /// </summary>
        public static string LatestComments {
            get {
                return ResourceManager.GetString("LatestComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string ManageTags {
            get {
                return ResourceManager.GetString("ManageTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing yet!.
        /// </summary>
        public static string NoComments {
            get {
                return ResourceManager.GetString("NoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, no matches :(.
        /// </summary>
        public static string NoMatches {
            get {
                return ResourceManager.GetString("NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official links.
        /// </summary>
        public static string OfficialLinks {
            get {
                return ResourceManager.GetString("OfficialLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unofficial links.
        /// </summary>
        public static string OtherLinks {
            get {
                return ResourceManager.GetString("OtherLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string PicturesTab {
            get {
                return ResourceManager.GetString("PicturesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an error.
        /// </summary>
        public static string ReportAnError {
            get {
                return ResourceManager.GetString("ReportAnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string ReportNotes {
            get {
                return ResourceManager.GetString("ReportNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (required).
        /// </summary>
        public static string ReportNotesRequired {
            get {
                return ResourceManager.GetString("ReportNotesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report type.
        /// </summary>
        public static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisions.
        /// </summary>
        public static string Revisions {
            get {
                return ResourceManager.GetString("Revisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share a link.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string ShowAllTags {
            get {
                return ResourceManager.GetString("ShowAllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all comments.
        /// </summary>
        public static string ViewAllComments {
            get {
                return ResourceManager.GetString("ViewAllComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View modifications.
        /// </summary>
        public static string ViewModifications {
            get {
                return ResourceManager.GetString("ViewModifications", resourceCulture);
            }
        }
    }
}
