//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VocaDb.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArtistTypeNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArtistTypeNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Model.Resources.ArtistTypeNames", typeof(ArtistTypeNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation producer.
        /// </summary>
        public static string Animator {
            get {
                return ResourceManager.GetString("Animator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band/unit.
        /// </summary>
        public static string Band {
            get {
                return ResourceManager.GetString("Band", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CeVIO.
        /// </summary>
        public static string CeVIO {
            get {
                return ResourceManager.GetString("CeVIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustrator.
        /// </summary>
        public static string Illustrator {
            get {
                return ResourceManager.GetString("Illustrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyricist.
        /// </summary>
        public static string Lyricist {
            get {
                return ResourceManager.GetString("Lyricist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other group.
        /// </summary>
        public static string OtherGroup {
            get {
                return ResourceManager.GetString("OtherGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other individual.
        /// </summary>
        public static string OtherIndividual {
            get {
                return ResourceManager.GetString("OtherIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other vocalist.
        /// </summary>
        public static string OtherVocalist {
            get {
                return ResourceManager.GetString("OtherVocalist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other voice synthesizer.
        /// </summary>
        public static string OtherVoiceSynthesizer {
            get {
                return ResourceManager.GetString("OtherVoiceSynthesizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music producer.
        /// </summary>
        public static string Producer {
            get {
                return ResourceManager.GetString("Producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utaite.
        /// </summary>
        public static string Utaite {
            get {
                return ResourceManager.GetString("Utaite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTAU.
        /// </summary>
        public static string UTAU {
            get {
                return ResourceManager.GetString("UTAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocaloid.
        /// </summary>
        public static string Vocaloid {
            get {
                return ResourceManager.GetString("Vocaloid", resourceCulture);
            }
        }
    }
}
