//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VocaDb.Model.Resources
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class ArtistValidationErrors
	{
		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ArtistValidationErrors()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Model.Resources.ArtistValidationErrors", typeof(ArtistValidationErrors).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Artist needs a description OR at least one external link as a reference..
		/// </summary>
		public static string NeedReferences
		{
			get
			{
				return ResourceManager.GetString("NeedReferences", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Artist type needs to be specified..
		/// </summary>
		public static string NeedType
		{
			get
			{
				return ResourceManager.GetString("NeedType", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to There is no need to add artist name both with and without the P suffix..
		/// </summary>
		public static string UnnecessaryPName
		{
			get
			{
				return ResourceManager.GetString("UnnecessaryPName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Artist needs a primary name..
		/// </summary>
		public static string UnspecifiedNames
		{
			get
			{
				return ResourceManager.GetString("UnspecifiedNames", resourceCulture);
			}
		}
	}
}
