//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VocaDb.Web.Resources.Views.SongList {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ImportNicoMylistStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImportNicoMylistStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.Resources.Views.SongList.ImportNicoMylistStrings", typeof(ImportNicoMylistStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that the URL is valid and points to a NicoNico MyList or RSS feed..
        /// </summary>
        public static string InvalidUrlError {
            get {
                return ResourceManager.GetString("InvalidUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mylist description.
        /// </summary>
        public static string MylistDescription {
            get {
                return ResourceManager.GetString("MylistDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NicoNico PV.
        /// </summary>
        public static string NicoPV {
            get {
                return ResourceManager.GetString("NicoPV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include only ranked songs (from NicoNicoDouga rankings).
        /// </summary>
        public static string OnlyRanked {
            get {
                return ResourceManager.GetString("OnlyRanked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include all songs in the list (not just ranked).
        /// </summary>
        public static string ParseAll {
            get {
                return ResourceManager.GetString("ParseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISSING.
        /// </summary>
        public static string SongMissing {
            get {
                return ResourceManager.GetString("SongMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs in the list.
        /// </summary>
        public static string SongsInList {
            get {
                return ResourceManager.GetString("SongsInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the songs are missing from VocaDB. You need to add all songs to the database before creating the list..
        /// </summary>
        public static string SongsMissingError {
            get {
                return ResourceManager.GetString("SongsMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create song list from NicoNicoDouga MyList.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse list.
        /// </summary>
        public static string UnableToParse {
            get {
                return ResourceManager.GetString("UnableToParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can be any NicoNicoDouga MyList, for example http://www.nicovideo.jp/mylist/1234567.
        /// </summary>
        public static string UrlDescription {
            get {
                return ResourceManager.GetString("UrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NicoNico mylist or RSS feed.
        /// </summary>
        public static string UrlLabel {
            get {
                return ResourceManager.GetString("UrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VocaDB song entry.
        /// </summary>
        public static string VocaDbEntry {
            get {
                return ResourceManager.GetString("VocaDbEntry", resourceCulture);
            }
        }
    }
}
