using System.Collections.Generic;
using VocaDb.Model.DataContracts;
using VocaDb.Model.DataContracts.Albums;
using VocaDb.Model.Domain;
using VocaDb.Model.Domain.ExtLinks;

namespace VocaDb.Model.Service.ExtSites
{

	/// <summary>
	/// Generates links to related useful sites.
	/// </summary>
	public class ExtLinkGenerator
	{

		public List<WebLinkContract> GenerateLinksForAlbum(AlbumContract album)
		{

			var links = new List<WebLinkContract>();

			links.Add(new WebLinkContract(
				string.Format("http://ekizo.mandarake.co.jp/shop/en/search.do?searchStrategy=keyword&action=keyword&doujin=all&keyword={0}", album.Name),
				string.Format(Resources.ExtSites.Search, "Mandarake") + " " + Resources.ExtSites.Autogenerated,
				WebLinkCategory.Commercial));

			return links;

		}

	}

}
