//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Search {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.Resources.Views.Search.IndexStrings", typeof(IndexStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string AlbumDetails {
            get {
                return ResourceManager.GetString("AlbumDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles.
        /// </summary>
        public static string AlbumTiles {
            get {
                return ResourceManager.GetString("AlbumTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album type.
        /// </summary>
        public static string AlbumType {
            get {
                return ResourceManager.GetString("AlbumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist type.
        /// </summary>
        public static string ArtistType {
            get {
                return ResourceManager.GetString("ArtistType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string EntryType {
            get {
                return ResourceManager.GetString("EntryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include derived voicebanks.
        /// </summary>
        public static string IncludeDerivedVoicebanks {
            get {
                return ResourceManager.GetString("IncludeDerivedVoicebanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In my collection.
        /// </summary>
        public static string InMyCollection {
            get {
                return ResourceManager.GetString("InMyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items of.
        /// </summary>
        public static string ItemsOf {
            get {
                return ResourceManager.GetString("ItemsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items per page.
        /// </summary>
        public static string ItemsPerPage {
            get {
                return ResourceManager.GetString("ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum rating score.
        /// </summary>
        public static string MinScore {
            get {
                return ResourceManager.GetString("MinScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More filters.
        /// </summary>
        public static string MoreFilters {
            get {
                return ResourceManager.GetString("MoreFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More recent than.
        /// </summary>
        public static string MoreRecentThan {
            get {
                return ResourceManager.GetString("MoreRecentThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only my followed artists.
        /// </summary>
        public static string OnlyMyFollowedArtists {
            get {
                return ResourceManager.GetString("OnlyMyFollowedArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only with PVs.
        /// </summary>
        public static string OnlyWithPVs {
            get {
                return ResourceManager.GetString("OnlyWithPVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tags.
        /// </summary>
        public static string ShowTags {
            get {
                return ResourceManager.GetString("ShowTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song type.
        /// </summary>
        public static string SongType {
            get {
                return ResourceManager.GetString("SongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string TagCategory {
            get {
                return ResourceManager.GetString("TagCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag information.
        /// </summary>
        public static string TagInformation {
            get {
                return ResourceManager.GetString("TagInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time(s).
        /// </summary>
        public static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top genres.
        /// </summary>
        public static string TopGenres {
            get {
                return ResourceManager.GetString("TopGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total score.
        /// </summary>
        public static string TotalScore {
            get {
                return ResourceManager.GetString("TotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type something....
        /// </summary>
        public static string TypeSomething {
            get {
                return ResourceManager.GetString("TypeSomething", resourceCulture);
            }
        }
    }
}
