//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Album {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.Resources.Views.Album.EditStrings", typeof(EditStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add track.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add artist.
        /// </summary>
        public static string ArAddArtist {
            get {
                return ResourceManager.GetString("ArAddArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist roles.
        /// </summary>
        public static string ArtistRolesTitle {
            get {
                return ResourceManager.GetString("ArtistRolesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists for song {0}.
        /// </summary>
        public static string ArtistsForSong {
            get {
                return ResourceManager.GetString("ArtistsForSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string ArtistsTab {
            get {
                return ResourceManager.GetString("ArtistsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog number.
        /// </summary>
        public static string BaCatNum {
            get {
                return ResourceManager.GetString("BaCatNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original language.
        /// </summary>
        public static string BaDefaultLanguageSelection {
            get {
                return ResourceManager.GetString("BaDefaultLanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album description.
        /// </summary>
        public static string BaDescription {
            get {
                return ResourceManager.GetString("BaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record type.
        /// </summary>
        public static string BaDiscType {
            get {
                return ResourceManager.GetString("BaDiscType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If unsure of which type to use, try to find out how the artists themselves call the album. For more elaborate descriptions, please refer to Wikipedia, Discogs or Musicbrainz..
        /// </summary>
        public static string BaDiscTypeExplanation {
            get {
                return ResourceManager.GetString("BaDiscTypeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main cover picture.
        /// </summary>
        public static string BaMainCoverPicture {
            get {
                return ResourceManager.GetString("BaMainCoverPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary name (in one or more languages).
        /// </summary>
        public static string BaNames {
            get {
                return ResourceManager.GetString("BaNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed types: {0}. Maximum size is {1} MB..
        /// </summary>
        public static string BaPictureInfo {
            get {
                return ResourceManager.GetString("BaPictureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        public static string BaReleaseDate {
            get {
                return ResourceManager.GetString("BaReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string BaReleaseDay {
            get {
                return ResourceManager.GetString("BaReleaseDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release event.
        /// </summary>
        public static string BaReleaseEvent {
            get {
                return ResourceManager.GetString("BaReleaseEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string BaReleaseMonth {
            get {
                return ResourceManager.GetString("BaReleaseMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string BaReleaseYear {
            get {
                return ResourceManager.GetString("BaReleaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic info.
        /// </summary>
        public static string BasicInfoTab {
            get {
                return ResourceManager.GetString("BasicInfoTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry status.
        /// </summary>
        public static string BaStatus {
            get {
                return ResourceManager.GetString("BaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External links.
        /// </summary>
        public static string BaWebLinks {
            get {
                return ResourceManager.GetString("BaWebLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes on this tab are saved immediately..
        /// </summary>
        public static string ChangesAreSavedImmediately {
            get {
                return ResourceManager.GetString("ChangesAreSavedImmediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this album?.
        /// </summary>
        public static string ConfirmDeleteAlbum {
            get {
                return ResourceManager.GetString("ConfirmDeleteAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to move this album to trash?.
        /// </summary>
        public static string ConfirmMoveToTrash {
            get {
                return ResourceManager.GetString("ConfirmMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit album {0}.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image preview.
        /// </summary>
        public static string ImagePreview {
            get {
                return ResourceManager.GetString("ImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string MediaTab {
            get {
                return ResourceManager.GetString("MediaTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to trash.
        /// </summary>
        public static string MoveToTrash {
            get {
                return ResourceManager.GetString("MoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string PiCreateNew {
            get {
                return ResourceManager.GetString("PiCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional pictures.
        /// </summary>
        public static string PicturesTab {
            get {
                return ResourceManager.GetString("PicturesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that the main picture is edited on the &quot;Basic Info&quot; tab. Please only upload pictures relevant to this album, nothing else..
        /// </summary>
        public static string PiPicturesGuide {
            get {
                return ResourceManager.GetString("PiPicturesGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add media.
        /// </summary>
        public static string PvAdd {
            get {
                return ResourceManager.GetString("PvAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string PvAuthor {
            get {
                return ResourceManager.GetString("PvAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use this page to add advertisements or crossfades related to this album..
        /// </summary>
        public static string PvIntro {
            get {
                return ResourceManager.GetString("PvIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PvName {
            get {
                return ResourceManager.GetString("PvName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string PvService {
            get {
                return ResourceManager.GetString("PvService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported services: Youtube, NicoNicoDouga, Vimeo, SoundCloud, Piapro and Bilibili..
        /// </summary>
        public static string PvSupportedServices {
            get {
                return ResourceManager.GetString("PvSupportedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string PvType {
            get {
                return ResourceManager.GetString("PvType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        public static string PvURL {
            get {
                return ResourceManager.GetString("PvURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track properties.
        /// </summary>
        public static string TrackPropertiesTitle {
            get {
                return ResourceManager.GetString("TrackPropertiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        public static string TracksTab {
            get {
                return ResourceManager.GetString("TracksTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: do not write the artist name or track number into the track name. Artists will be specified separately..
        /// </summary>
        public static string TrAddTrackHelp {
            get {
                return ResourceManager.GetString("TrAddTrackHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc.
        /// </summary>
        public static string TrDiscHead {
            get {
                return ResourceManager.GetString("TrDiscHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TrNameHead {
            get {
                return ResourceManager.GetString("TrNameHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set artists for selected tracks.
        /// </summary>
        public static string TrSetArtists {
            get {
                return ResourceManager.GetString("TrSetArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string TrTrackHead {
            get {
                return ResourceManager.GetString("TrTrackHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click track name to edit artists..
        /// </summary>
        public static string TrTrackNameHelp {
            get {
                return ResourceManager.GetString("TrTrackNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save properties.
        /// </summary>
        public static string UnableToSaveProperties {
            get {
                return ResourceManager.GetString("UnableToSaveProperties", resourceCulture);
            }
        }
    }
}
