//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VocaDb.Web.Resources.Domain.ReleaseEvents
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class EventCategoryNames
	{
		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal EventCategoryNames()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.Resources.Domain.ReleaseEvents.EventCategoryNames", typeof(EventCategoryNames).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Album release fair.
		/// </summary>
		public static string AlbumRelease
		{
			get
			{
				return ResourceManager.GetString("AlbumRelease", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Character anniversary.
		/// </summary>
		public static string Anniversary
		{
			get
			{
				return ResourceManager.GetString("Anniversary", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Club.
		/// </summary>
		public static string Club
		{
			get
			{
				return ResourceManager.GetString("Club", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Concert.
		/// </summary>
		public static string Concert
		{
			get
			{
				return ResourceManager.GetString("Concert", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Contest.
		/// </summary>
		public static string Contest
		{
			get
			{
				return ResourceManager.GetString("Contest", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Convention.
		/// </summary>
		public static string Convention
		{
			get
			{
				return ResourceManager.GetString("Convention", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Other.
		/// </summary>
		public static string Other
		{
			get
			{
				return ResourceManager.GetString("Other", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unspecified.
		/// </summary>
		public static string Unspecified
		{
			get
			{
				return ResourceManager.GetString("Unspecified", resourceCulture);
			}
		}
	}
}
