//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.User
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class MessagesStrings
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal MessagesStrings()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.Resources.Views.User.MessagesStrings", typeof(MessagesStrings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Body.
		/// </summary>
		public static string Body
		{
			get
			{
				return ResourceManager.GetString("Body", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Click subject to view the message..
		/// </summary>
		public static string ClickSubjectToView
		{
			get
			{
				return ResourceManager.GetString("ClickSubjectToView", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Compose.
		/// </summary>
		public static string Compose
		{
			get
			{
				return ResourceManager.GetString("Compose", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Date.
		/// </summary>
		public static string Date
		{
			get
			{
				return ResourceManager.GetString("Date", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete selected.
		/// </summary>
		public static string DeleteSelected
		{
			get
			{
				return ResourceManager.GetString("DeleteSelected", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to From.
		/// </summary>
		public static string From
		{
			get
			{
				return ResourceManager.GetString("From", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to from.
		/// </summary>
		public static string FromLC
		{
			get
			{
				return ResourceManager.GetString("FromLC", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to High priority.
		/// </summary>
		public static string HighPriority
		{
			get
			{
				return ResourceManager.GetString("HighPriority", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Messages.
		/// </summary>
		public static string Messages
		{
			get
			{
				return ResourceManager.GetString("Messages", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Error while sending message..
		/// </summary>
		public static string MessageSendError
		{
			get
			{
				return ResourceManager.GetString("MessageSendError", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The message has been sent..
		/// </summary>
		public static string MessageSent
		{
			get
			{
				return ResourceManager.GetString("MessageSent", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Notifications.
		/// </summary>
		public static string Notifications
		{
			get
			{
				return ResourceManager.GetString("Notifications", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Received.
		/// </summary>
		public static string Received
		{
			get
			{
				return ResourceManager.GetString("Received", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Reply.
		/// </summary>
		public static string Reply
		{
			get
			{
				return ResourceManager.GetString("Reply", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Send.
		/// </summary>
		public static string Send
		{
			get
			{
				return ResourceManager.GetString("Send", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Sent.
		/// </summary>
		public static string Sent
		{
			get
			{
				return ResourceManager.GetString("Sent", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Subject.
		/// </summary>
		public static string Subject
		{
			get
			{
				return ResourceManager.GetString("Subject", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to To.
		/// </summary>
		public static string To
		{
			get
			{
				return ResourceManager.GetString("To", resourceCulture);
			}
		}
	}
}
