//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.User
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class MySettingsStrings
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal MySettingsStrings()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.Resources.Views.User.MySettingsStrings", typeof(MySettingsStrings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to About me.
		/// </summary>
		public static string AboutMe
		{
			get
			{
				return ResourceManager.GetString("AboutMe", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Access key.
		/// </summary>
		public static string AccessKey
		{
			get
			{
				return ResourceManager.GetString("AccessKey", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Access key can be used to log in to your account from various other services without revealing your actual password.
		///				You can regenerate your access key at any time - this will invalidate the previous access key.
		///				Keep your access key secret! If you suspect your access key has been discovered by someone else, please reset it immediately..
		/// </summary>
		public static string AccessKeyDescription
		{
			get
			{
				return ResourceManager.GetString("AccessKeyDescription", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Account settings.
		/// </summary>
		public static string AccountSettings
		{
			get
			{
				return ResourceManager.GetString("AccountSettings", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Add row.
		/// </summary>
		public static string AddKnownLanguage
		{
			get
			{
				return ResourceManager.GetString("AddKnownLanguage", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Allow my username to be shown in the recent activity list..
		/// </summary>
		public static string AnonymousActivity
		{
			get
			{
				return ResourceManager.GetString("AnonymousActivity", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to (Automatic).
		/// </summary>
		public static string Automatic
		{
			get
			{
				return ResourceManager.GetString("Automatic", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Change password.
		/// </summary>
		public static string ChangePassword
		{
			get
			{
				return ResourceManager.GetString("ChangePassword", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to You only need to fill these if you want to change your password..
		/// </summary>
		public static string ChangePasswordNotice
		{
			get
			{
				return ResourceManager.GetString("ChangePasswordNotice", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Connect.
		/// </summary>
		public static string Connect
		{
			get
			{
				return ResourceManager.GetString("Connect", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Connectivity.
		/// </summary>
		public static string Connectivity
		{
			get
			{
				return ResourceManager.GetString("Connectivity", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Date and number formatting.
		/// </summary>
		public static string CultureName
		{
			get
			{
				return ResourceManager.GetString("CultureName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Current password.
		/// </summary>
		public static string CurrentPass
		{
			get
			{
				return ResourceManager.GetString("CurrentPass", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Preferred display language.
		/// </summary>
		public static string DefaultLanguageSelection
		{
			get
			{
				return ResourceManager.GetString("DefaultLanguageSelection", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Email.
		/// </summary>
		public static string Email
		{
			get
			{
				return ResourceManager.GetString("Email", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Not shown to other users, used by gravatar and password resets.
		/// </summary>
		public static string EmailNote
		{
			get
			{
				return ResourceManager.GetString("EmailNote", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Email notifications for private messages.
		/// </summary>
		public static string EmailOptions
		{
			get
			{
				return ResourceManager.GetString("EmailOptions", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This email address already belongs to another user. If it is your address, contact support..
		/// </summary>
		public static string EmailTaken
		{
			get
			{
				return ResourceManager.GetString("EmailTaken", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to External links.
		/// </summary>
		public static string ExternalLinks
		{
			get
			{
				return ResourceManager.GetString("ExternalLinks", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Interface.
		/// </summary>
		public static string Interface
		{
			get
			{
				return ResourceManager.GetString("Interface", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Interface language.
		/// </summary>
		public static string InterfaceLanguageSelection
		{
			get
			{
				return ResourceManager.GetString("InterfaceLanguageSelection", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Please check the format of the email address..
		/// </summary>
		public static string InvalidEmail
		{
			get
			{
				return ResourceManager.GetString("InvalidEmail", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Live preview.
		/// </summary>
		public static string LivePreview
		{
			get
			{
				return ResourceManager.GetString("LivePreview", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Location.
		/// </summary>
		public static string Location
		{
			get
			{
				return ResourceManager.GetString("Location", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to My settings.
		/// </summary>
		public static string MySettingsTitle
		{
			get
			{
				return ResourceManager.GetString("MySettingsTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to New password.
		/// </summary>
		public static string NewPass
		{
			get
			{
				return ResourceManager.GetString("NewPass", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to New password again.
		/// </summary>
		public static string NewPassAgain
		{
			get
			{
				return ResourceManager.GetString("NewPassAgain", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Passwords must match.
		/// </summary>
		public static string PasswordsMustMatch
		{
			get
			{
				return ResourceManager.GetString("PasswordsMustMatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Preferred streaming service.
		/// </summary>
		public static string PreferredVideoService
		{
			get
			{
				return ResourceManager.GetString("PreferredVideoService", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Privacy options.
		/// </summary>
		public static string Privacy
		{
			get
			{
				return ResourceManager.GetString("Privacy", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Profile.
		/// </summary>
		public static string Profile
		{
			get
			{
				return ResourceManager.GetString("Profile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Allow others to see which albums I own..
		/// </summary>
		public static string PublicAlbumCollection
		{
			get
			{
				return ResourceManager.GetString("PublicAlbumCollection", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Allow everyone to see my song and album ratings..
		/// </summary>
		public static string PublicRatings
		{
			get
			{
				return ResourceManager.GetString("PublicRatings", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Really reset code?.
		/// </summary>
		public static string ReallyReset
		{
			get
			{
				return ResourceManager.GetString("ReallyReset", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Reset.
		/// </summary>
		public static string Reset
		{
			get
			{
				return ResourceManager.GetString("Reset", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Settings updated.
		/// </summary>
		public static string SettingsUpdated
		{
			get
			{
				return ResourceManager.GetString("SettingsUpdated", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Theme.
		/// </summary>
		public static string Theme
		{
			get
			{
				return ResourceManager.GetString("Theme", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unable to save settings. Please correct the errors and try again..
		/// </summary>
		public static string UnableToSave
		{
			get
			{
				return ResourceManager.GetString("UnableToSave", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Maximum number of unread notifications.
		/// </summary>
		public static string UnreadNotificationsToKeep
		{
			get
			{
				return ResourceManager.GetString("UnreadNotificationsToKeep", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Username.
		/// </summary>
		public static string Username
		{
			get
			{
				return ResourceManager.GetString("Username", resourceCulture);
			}
		}
	}
}
