//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VocaDb.Web.Resources.Domain
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class EntryReportTypeNames
	{
		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal EntryReportTypeNames()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.Resources.Domain.EntryReportTypeNames", typeof(EntryReportTypeNames).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Broken PV.
		/// </summary>
		public static string BrokenPV
		{
			get
			{
				return ResourceManager.GetString("BrokenPV", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Duplicate entry.
		/// </summary>
		public static string Duplicate
		{
			get
			{
				return ResourceManager.GetString("Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Inappropriate content.
		/// </summary>
		public static string Inappropriate
		{
			get
			{
				return ResourceManager.GetString("Inappropriate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid or missing information.
		/// </summary>
		public static string InvalidInfo
		{
			get
			{
				return ResourceManager.GetString("InvalidInfo", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Malicious IP.
		/// </summary>
		public static string MaliciousIP
		{
			get
			{
				return ResourceManager.GetString("MaliciousIP", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Other (specify in notes).
		/// </summary>
		public static string Other
		{
			get
			{
				return ResourceManager.GetString("Other", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ownership claim.
		/// </summary>
		public static string OwnershipClaim
		{
			get
			{
				return ResourceManager.GetString("OwnershipClaim", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Restricted editing.
		/// </summary>
		public static string RemovePermissions
		{
			get
			{
				return ResourceManager.GetString("RemovePermissions", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Spamming.
		/// </summary>
		public static string Spamming
		{
			get
			{
				return ResourceManager.GetString("Spamming", resourceCulture);
			}
		}
	}
}
