//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VocaDb.Model.Resources.Messages
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class UserAccountStrings
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal UserAccountStrings()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Model.Resources.Messages.UserAccountStrings", typeof(UserAccountStrings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Welcome to {0}, please verify your email..
		/// </summary>
		public static string AccountCreatedSubject
		{
			get
			{
				return ResourceManager.GetString("AccountCreatedSubject", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to You (or someone who knows your email address) has requested to reset your password on VocaDB.
		///You can perform this action at {0} . If the link doesn&apos;t work, try copying it to the address bar. If you did not request this action, you can ignore this message..
		/// </summary>
		public static string PasswordResetBody
		{
			get
			{
				return ResourceManager.GetString("PasswordResetBody", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Password reset requested..
		/// </summary>
		public static string PasswordResetSubject
		{
			get
			{
				return ResourceManager.GetString("PasswordResetSubject", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Please click the link below to verify your email at {0}.
		///{1}?token={2}.
		/// </summary>
		public static string VerifyEmailBody
		{
			get
			{
				return ResourceManager.GetString("VerifyEmailBody", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Verify your email at {0}..
		/// </summary>
		public static string VerifyEmailSubject
		{
			get
			{
				return ResourceManager.GetString("VerifyEmailSubject", resourceCulture);
			}
		}
	}
}
