//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelperRes
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class HelperStrings
	{
		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal HelperStrings()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocaDb.Web.Resources.Helpers.HelperStrings", typeof(HelperStrings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to added.
		/// </summary>
		public static string Added
		{
			get
			{
				return ResourceManager.GetString("Added", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This entry is a draft..
		/// </summary>
		public static string DraftIconTitle
		{
			get
			{
				return ResourceManager.GetString("DraftIconTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This entry is a draft. You can help by editing the entry and adding the missing information..
		/// </summary>
		public static string DraftMessage
		{
			get
			{
				return ResourceManager.GetString("DraftMessage", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This entry is missing the following information:.
		/// </summary>
		public static string EntryIsMissingInformation
		{
			get
			{
				return ResourceManager.GetString("EntryIsMissingInformation", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This entry contains all the required information..
		/// </summary>
		public static string EntryValidationNoErrors
		{
			get
			{
				return ResourceManager.GetString("EntryValidationNoErrors", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This entry contains all the required information to be marked as finalized (not draft)..
		/// </summary>
		public static string EntryValidationNoErrorsDraft
		{
			get
			{
				return ResourceManager.GetString("EntryValidationNoErrorsDraft", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Details.
		/// </summary>
		public static string EntryValidationWarningDetails
		{
			get
			{
				return ResourceManager.GetString("EntryValidationWarningDetails", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to GitHub-flavored Markdown.
		/// </summary>
		public static string GitHubMarkdown
		{
			get
			{
				return ResourceManager.GetString("GitHubMarkdown", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to is supported for formatting.
		/// </summary>
		public static string IsSupportedForFormatting
		{
			get
			{
				return ResourceManager.GetString("IsSupportedForFormatting", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Language.
		/// </summary>
		public static string NameLangTitle
		{
			get
			{
				return ResourceManager.GetString("NameLangTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to New row.
		/// </summary>
		public static string NameNewRow
		{
			get
			{
				return ResourceManager.GetString("NameNewRow", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Name (required).
		/// </summary>
		public static string NameValueTitle
		{
			get
			{
				return ResourceManager.GetString("NameValueTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Return without saving.
		/// </summary>
		public static string ReturnWithoutSaving
		{
			get
			{
				return ResourceManager.GetString("ReturnWithoutSaving", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Save changes.
		/// </summary>
		public static string SaveChanges
		{
			get
			{
				return ResourceManager.GetString("SaveChanges", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to guide.
		/// </summary>
		public static string SeeGuide
		{
			get
			{
				return ResourceManager.GetString("SeeGuide", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to for more information..
		/// </summary>
		public static string SeeGuidePost
		{
			get
			{
				return ResourceManager.GetString("SeeGuidePost", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to See the.
		/// </summary>
		public static string SeeGuidePre
		{
			get
			{
				return ResourceManager.GetString("SeeGuidePre", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Approved entries have been inspected by a trusted user. Editing of approved entries is limited..
		/// </summary>
		public static string StatusDescriptionApproved
		{
			get
			{
				return ResourceManager.GetString("StatusDescriptionApproved", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Draft entries are missing some required information..
		/// </summary>
		public static string StatusDescriptionDraft
		{
			get
			{
				return ResourceManager.GetString("StatusDescriptionDraft", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Finished entries contain all the required information but haven&apos;t been approved yet..
		/// </summary>
		public static string StatusDescriptionFinished
		{
			get
			{
				return ResourceManager.GetString("StatusDescriptionFinished", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Locked entries can only be edited by staff members..
		/// </summary>
		public static string StatusDescriptionLocked
		{
			get
			{
				return ResourceManager.GetString("StatusDescriptionLocked", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Allowed types: {0}. Maximum size is {1} MB. Please respect copyrights and mention the image source in notes/description if possible..
		/// </summary>
		public static string UploadPictureInfo
		{
			get
			{
				return ResourceManager.GetString("UploadPictureInfo", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Category.
		/// </summary>
		public static string WebLinkCategoryTitle
		{
			get
			{
				return ResourceManager.GetString("WebLinkCategoryTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Description.
		/// </summary>
		public static string WebLinkDescriptionTitle
		{
			get
			{
				return ResourceManager.GetString("WebLinkDescriptionTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to New row.
		/// </summary>
		public static string WebLinkNewRow
		{
			get
			{
				return ResourceManager.GetString("WebLinkNewRow", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to URL.
		/// </summary>
		public static string WebLinkUrlTitle
		{
			get
			{
				return ResourceManager.GetString("WebLinkUrlTitle", resourceCulture);
			}
		}
	}
}
